#!/bin/bash

echo ""
echo "Updating LDbase modules and configuration..."
echo ""

echo ""
echo "Updating all LDbase modules..."
cd /var/www/html/drupal
composer update --no-interaction
cp composer.* /ldbase_deployment/assets/

echo ""
echo "Updating LDbase configuration..."
cd /var/www/html/drupal
/var/www/html/drupal/vendor/bin/drush config:export --destination=/var/www/html/drupal/web/libraries/ldbase_config/sync

echo ""
echo "Done. LDbase modules and configuration updated."
echo "Please add, commit and push new composer.json and composer.lock files in /ldbase_deployment"
echo "Please add, commit and push new configuration in /var/www/html/drupal/web/libraries/ldbase_config"
