#!/bin/bash

echo ""
echo "Importing custom configurations into LDbase..."
echo ""

cd /var/www/html/drupal/
/var/www/html/drupal/vendor/bin/drupal config:import --directory=/var/www/html/drupal/web/libraries/ldbase_config/sync

echo ""
echo "Done. Custom configurations imported."
