#!/bin/bash

echo ""
echo "Destroying and rebuilding LDbase Drupal installation..."
echo ""

echo ""
echo "Rebuilding database..."
mv /var/www/html/drupal/web/sites/default/settings.php /root/settings.php
rm -rf /var/www/html/drupal
php /ldbase_deployment/build/database-tiller.php
mv /root/settings.php /var/www/html/drupal/web/sites/default/settings.php

echo ""
echo "Configuring LDbase..."
sh /ldbase_deployment/build/drupal-custom-codebase-config.sh
sh /ldbase_deployment/build/drupal-custom-system-config.sh

echo ""
echo "Done. LDbase rebuilt."
