#!/bin/bash

cd /var/www/html/drupal

echo "Adding Drupal 9 requirements to composer.json..."
composer require drupal/core-dev:^9.2.0 --dev --no-update --update-with-dependencies --no-interaction
composer require drupal/core:^9.2.0 drupal/core-recommended:^9.2.0 drupal/core-composer-scaffold:^9.2.0 drupal/core-project-message:^9.2.0 --no-update --update-with-dependencies --no-interaction
composer require drupal/console:1.9.7 --no-update --update-with-dependencies --no-interaction

echo "Updating to Drupal 9 via composer update..."
composer update --no-interaction

echo "Updating database schema..."
drush -y updb
drush cr

echo "Done!"
