#!/bin/bash

echo ""
echo "Exporting custom configurations from LDbase..."
echo ""

/var/www/html/drupal/vendor/bin/drush config:export --destination=/var/www/html/drupal/web/libraries/ldbase_config/sync

echo ""
echo "Done. Custom configurations exported."
