#!/bin/bash

echo ""
echo "Destroying and rebuilding LDbase Drupal installation..."
echo ""

echo ""
echo "Destroying Drupal filesystem and database..."
rm -rf /var/www/html/drupal
mysql --user="${DATABASE_ROOT_USER}" \
        --password="${DATABASE_ROOT_PASS}" \
        --host="${DATABASE_ENDPOINT}" \
        --execute="DROP DATABASE ldbasedb;"

echo ""
echo "Rebuilding Drupal..."
sh /ldbase_deployment/build/drupal-mysql-config.sh
sh /ldbase_deployment/build/drupal-core-download.sh
sh /ldbase_deployment/build/drupal-core-config.sh

echo ""
echo "Configuring LDbase..."
sh /ldbase_deployment/build/drupal-custom-codebase-config.sh
sh /ldbase_deployment/build/drupal-custom-system-config.sh

echo ""
echo "Done. LDbase rebuilt."
