#!/bin/bash

# Install PHP 7.4
add-apt-repository -y ppa:ondrej/php
apt-get -y update
apt-get -y install php7.4 php7.4-dev php7.4-gd php7.4-soap php7.4-mysql php7.4-mbstring php7.4-zip php7.4-curl php7.4-xml

# Update to Drupal 9
cd /var/www/html/drupal
rm composer.*
cp /ldbase_deployment/assets/drupal9.composer.json .
mv drupal9.composer.json composer.json
composer install
