#!/bin/bash

cd /var/www/html/drupal/; /var/www/html/drupal/vendor/bin/drush config:import --source=/var/www/html/drupal/web/libraries/ldbase_config/sync

if [ "$VAGRANT" = true ]
then 
  /var/www/html/drupal/vendor/bin/drush config:set "s3fs.settings" use_customhost 1 -y
  /var/www/html/drupal/vendor/bin/drush config:set "s3fs.settings" hostname '127.0.0.1:9000' -y
fi
