#!/bin/bash

echo ""
echo "Refreshing LDbase..."
echo ""

echo ""
echo "Rebuilding Drupal database..."
cd /var/www/html/drupal
/var/www/html/drupal/vendor/bin/drupal database:drop --no-interaction
sh /ldbase_deployment/build/drupal.install.sh

echo ""
echo "Updating LDbase custom modules..."
cd /ldbase_deployment; git pull
cd /var/www/html/drupal
rm composer.*
cp /ldbase_deployment/assets/composer.json .
composer update --no-interaction

echo ""
echo "Updating LDbase system configuration..."
sh /ldbase_deployment/build/drupal.config.sh

echo ""
echo "Done. LDbase refreshed."
