#!/bin/bash

echo ""
echo "Refreshing LDbase..."
echo ""

echo ""
echo "Rebuilding Drupal database..."
cd /var/www/html/drupal
/var/www/html/drupal/vendor/bin/drupal database:drop --no-interaction
sh /root/ldbase_deployment/build/drupal-core-config.sh

echo ""
echo "Updating LDbase custom modules..."
sh /root/ldbase_deployment/build/ldbase-custom-codebase-update.sh

echo ""
echo "Updating LDbase system configuration..."
sh /root/ldbase_deployment/build/drupal-custom-system-config.sh

echo ""
echo "Done. LDbase refreshed."
